/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verhora;

import java.awt.Color;

/**
 *
 * @author daniel
 */
public class monitores extends javax.swing.JFrame {

    public String humedad = "";
    public String temperatura = "";
    public String puerta = "";
    public String liquidos = "";
    public String fecha = "";
    public String hora = "";
  
    /**
     * Creates new form monitores
     */
    public monitores() {
        initComponents();
//        this.getContentPane().setBackground(Color.orange);

    }
    public void EventoHumedad(String eve){
//        if (eve=="blink"){
        LHumedad.setForeground(Color.RED);
//        }
    }
    public void EventoTemperatura(String eve){
        if (eve=="blink"){
        LTemperatura.setForeground(Color.RED);
        }
    }
     public void EventoPuerta(String eve){
        if (eve=="blink"){
        LPuerta.setForeground(Color.RED);
        }
    }
      public void EventoLiquidos(String eve){
        if (eve=="blink"){
        LLiquidos.setForeground(Color.RED);
        }
    }
    public void SetHumedad() {
        LHumedad.setText(humedad);

    }

    public void SetTemperatura() {
        LTemperatura.setText(temperatura);

    }

    public void SetPuerta() {
        LPuerta.setText(puerta);

    }

    public void SetLiquidos() {
        LLiquidos.setText(liquidos);

    }

    public void SetFecha() {
        LFecha.setText(fecha);

    }

    public void SetHora() {
        LHora.setText(hora);

    }
// 
//      // Set the Drawing JPanel as the JFrame's content-pane
//      Container cp = getContentPane();
//      cp.add(canvas);
//      // or "setContentPane(canvas);"
// 
//      setDefaultCloseOperation(EXIT_ON_CLOSE);   // Handle the CLOSE button
//      pack();              // Either pack() the components; or setSize()
//      setTitle("......");  // "super" JFrame sets the title
//      setVisible(true);    // "super" JFrame show
//   }
// 
//   /**
//    * Define inner class DrawCanvas, which is a JPanel used for custom drawing.
//    */
// 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        LTemperatura = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LHumedad = new javax.swing.JLabel();
        LPuerta = new javax.swing.JLabel();
        LLiquidos = new javax.swing.JLabel();
        T = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        Puerta = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LHora = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitoreo de Humedad - Temperatura");
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 255, 102));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LTemperatura.setText("Temperatura");

        jButton1.setText("Configuración");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LHumedad.setText("Humedad");

        LPuerta.setText("Puerta:");

        LLiquidos.setText("Liquidos");

        T.setText("Temperatura:");

        H.setText("Humedad:");

        Puerta.setText("Puerta:");

        l.setText("Liquidos");

        jLabel1.setText("Fecha");

        LFecha.setText("fecha");

        jLabel2.setText("Hora");

        LHora.setText("hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(T)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTemperatura)
                        .addGap(77, 77, 77)
                        .addComponent(H)
                        .addGap(18, 18, 18)
                        .addComponent(LHumedad)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LFecha)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LHora)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Puerta)
                        .addGap(42, 42, 42)
                        .addComponent(LPuerta)
                        .addGap(110, 110, 110)
                        .addComponent(l)
                        .addGap(27, 27, 27)
                        .addComponent(LLiquidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTemperatura)
                    .addComponent(LHumedad)
                    .addComponent(H)
                    .addComponent(T)
                    .addComponent(jLabel1)
                    .addComponent(LFecha)
                    .addComponent(jLabel2)
                    .addComponent(LHora))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPuerta)
                    .addComponent(LLiquidos)
                    .addComponent(Puerta)
                    .addComponent(l)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LTemperatura.getAccessibleContext().setAccessibleParent(LTemperatura);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        Configuracion rs = new Configuracion();
        rs.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(monitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

// Set the Drawing JPanel as the JFrame's content-pane
//      Container cp = getContentPane();
//                new monitores().setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel H;
    private javax.swing.JLabel LFecha;
    private javax.swing.JLabel LHora;
    private javax.swing.JLabel LHumedad;
    private javax.swing.JLabel LLiquidos;
    private javax.swing.JLabel LPuerta;
    private javax.swing.JLabel LTemperatura;
    private javax.swing.JLabel Puerta;
    private javax.swing.JLabel T;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel l;
    // End of variables declaration//GEN-END:variables
}
